name: the_project_v3
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core
  dartz: any
  equatable: any

  # State Management
  flutter_bloc: any

  # Blockchain
  web3dart: ^2.7.3

  # Secure Storage
  flutter_secure_storage: any

  # UI
  cupertino_icons: any
  flutter_svg: any
  page_transition: any

  # Security
  flutter_jailbreak_detection: any
  http_certificate_pinning: any

  # KYC
  idenfy_sdk_flutter: any

  # QR Code
  mobile_scanner: any
  qr_flutter: any
  qr_code_scanner: any

  # Environment variables
  flutter_dotenv: any

  # Service Locator
  get_it: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/